import os
import subprocess
import tempfile
import uuid
from loguru import logger
from app.core.exceptions import UnsupportedFileTypeError
from app.extractor.pdf import PDFExtractor

class WordExtractor:
    """
    Extracts text from Microsoft Word documents.
    Converts .doc and .docx files to PDF using LibreOffice in a headless process,
    then leverages the PDFExtractor to preserve hierarchical alignment and spacing perfectly.
    """
    
    def extract(self, raw_input: bytes) -> str:
        """
        Extracts raw text from a word document by converting to PDF first.
        """
        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                input_path = os.path.join(tmpdir, "input.docx")
                with open(input_path, "wb") as f:
                    f.write(raw_input)
                    
                profile_dir = os.path.join(tmpdir, "profile")
                
                logger.info("Converting Word document to PDF using LibreOffice...")
                cmd = [
                    "libreoffice",
                    f"-env:UserInstallation=file://{profile_dir}",
                    "--headless",
                    "--convert-to", "pdf",
                    "input.docx",
                    "--outdir", tmpdir
                ]
                
                result = subprocess.run(
                    cmd, 
                    cwd=tmpdir, 
                    stdout=subprocess.PIPE, 
                    stderr=subprocess.PIPE, 
                    timeout=30
                )
                
                if result.returncode != 0:
                    err_msg = result.stderr.decode('utf-8', errors='ignore')
                    logger.error(f"LibreOffice conversion failed: {err_msg}")
                    raise RuntimeError(f"LibreOffice conversion failed: {err_msg}")
                    
                pdf_path = os.path.join(tmpdir, "input.pdf")
                if not os.path.exists(pdf_path):
                    raise RuntimeError("PDF file was not generated by LibreOffice")
                    
                with open(pdf_path, "rb") as f:
                    pdf_bytes = f.read()
                    
            logger.info("Successfully converted Word document to PDF. Passing to PDFExtractor.")
            pdf_extractor = PDFExtractor()
            return pdf_extractor.extract(pdf_bytes)
            
        except subprocess.TimeoutExpired:
            logger.error("LibreOffice conversion timed out after 30 seconds.")
            raise UnsupportedFileTypeError("Failed to extract text: Document conversion timed out.")
        except Exception as e:
            logger.error(f"Failed to extract text from Word document via PDF conversion: {e}")
            raise UnsupportedFileTypeError(f"Failed to extract text from Word document. Error: {e}")
